- lua/luaconf.h
Fix compile error
> In file included from drivers/lunatik/lua/lctype.c:13:0:
> drivers/lunatik/lua/lctype.h:73:37: error: ‘UCHAR_MAX’ undeclared here (not in a function)
> LUAI_DDEC const lu_byte luai_ctype_[UCHAR_MAX + 2];
>                                     ^~~~~~~~~
> scripts/Makefile.build:298: recipe for target 'drivers/lunatik/lua/lctype.o' failed
> make[2]: *** [drivers/lunatik/lua/lctype.o] Error 1
> scripts/Makefile.build:549: recipe for target 'drivers/lunatik' failed
> Fix ‘UCHAR_MAX’ undeclared

- lua/loslib.c
- lua/luaconf.h
Since Linux version 5.6.0, 32-bit time interfaces have been deprecated due to y2k38
https://www.kernel.org/doc/html/latest/core-api/timekeeping.html#deprecated-time-interfaces
> Stop using the deprecated 32-bit time interfaces when using kernel versions >= 5.6.0

- README.md
- examples/systrack.lua
* see https://github.com/luainkernel/lunatik/issues/96
> limit the syscalls to track on examples/systrack.lua

- Makefile
Update the makefile so that
```
make KDIR=/path/to/kernel/source
```
will build lunatik modules for the version of Linux kernel located there
> Enable building against a custom kernel

- Makefile
When running `make clean` and other rules that use `rm` to remove fils/folder, these give out errors if the reffered file/folder does not exist. Hence this PR adds `-f` to ignore nonexistent files and arguments.
> add rm, install and mkdir variables to makefile

- lib/luaxdp.c
> fix luaxdp BTF flags for kernel >= 6.9.0

- lib/lualinux.c
- lib/luasocket.c
Currently, the `AF_PACKET` socket does not allow modifying the `sockaddr_ll` to specify a particular device. This changes allow the application to pass the interface as the address argument of `send`.
> support an specific device when using AF_PACKET

- Makefile
When using `make` instead of `${MAKE}`, running `make -j4` (for example) returns:
```
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
```
> Allow parallel compilation with make -j

- lib/luanetfilter.h
- lib/luaxdp.c
- lunatik.h
- lunatik_obj.c
* remove lunatik_requiref() API
* now it's not needed to require the obj lib before indexing an RCU table
> require lib automatically when clonning objects

- Makefile
- README.md
Makefile miss installing ebpf https.o program.
install https.o in /usr/local/lib/bpf/lunatik since xdp-tools by default install ebpf program in /usr/local/lib/bpf.
> install ebpf https.o to /usr/local/lib/bpf/lunatik

- tools/debian_kernel_postinst_lunatik.sh
This avoids re-downloading kernel sources on each attempt in case anything goes wrong.
> Only delete temporary files on success

- lib/luasocket.c
* sa_data_min field was actual introduced on v5.15.150
> fix struct sockaddr version check

- Makefile
The MODULES_BUILD_PATH variable was used to designate both the location of kernel headers and where to copy `/sys/kernel/btf/vmlinux` when
`btf_install` target. when building and installing a module for the same machine, they are indeed the same; however they differ if we pass
a MODULES_BUILD_PATH externally, for example the kernel source, with a config for a different target platform.
The default values remain the same as they were.
> separate kernel build directory and module build path

- README.md
- lib/luanotifier.c
This enables registration of notifier blocks for virtual terminal events. Here's an example of use:
```lua
local notifier = require 'notifier'
local notify = notifier.notify
local vt_ev = notifier.vt
function vt_monitor (event, c, vc_num)
print (string.format("event=%d, c=%d, vc_num=%d", event, c, vc_num))
return notify.OK end
notifier.vterm (vt_monitor)
```
> added vt support to luanotifier

- lib/luacompletion.c
`MAX_SCHEDULE_TIMEOUT` is defined at [`linux/sched.h`](https://elixir.bootlin.com/linux/v6.15-rc3/source/include/linux/sched.h#L324) since [v.2.1](https://elixir.bootlin.com/linux/2.1.133pre5/source/include/linux/sched.h#L120).
> make MAX_SCHEDULE_TIMEOUT definition available

- Kbuild
- lib/luathread.c
- amend asm compilation for mips/mipsel
- condition multi-cpu task management to allow builds for 1-cpu target machines
Relates to [luainkernel/openwrt_feed/pull/5](https://github.com/luainkernel/openwrt_feed/pull/5)
> Adjust build for mips(el) + 1-cpu targets

- lib/luasocket.c
* we were passing a pointer to an out of scope var ahead
> fix spurious address on luasocket_send()

- lib/luaxdp.c
fixes : #262 
This pull request fixes a build failure when compiling Lunatik on Linux kernels older than 6.4.0 (e.g., Debian 12 with 6.1.x).
The `luaxdp_exit()` function references `luaxdp_runtimes`  which is only available in Linux >= 6.4. This causes compilation error.
Added an version guard in before using the `luaxdp_runtimes` variable.
> Fix :  add kernel version guard to luaxdp_exit() for compatibility with < 6.4

- lib/luanetfilter.h
- lunatik.h
moving the marco `lunatik_setstring` to the header `lunatik.h`, which giving access privileges to all c codes.
> move lunatik_setstring into lunatik.h

- lib/luanetfilter.c
- lib/luanetfilter.h
- lib/luaxtable.c
- lunatik.h
This pull request refactors the Lua-Netfilter integration by replacing `luanetfilter_*` macros with equivalent `lunatik_*` macros across the codebase. This change consolidates functionality into the `lunatik.h` file, simplifying maintenance and improving consistency.
* **Macro replacement in `lib/luanetfilter.c`:** Updated calls to `luanetfilter_setinteger` and `luanetfilter_optinteger` with `lunatik_setinteger` and `lunatik_optinteger` respectively, ensuring consistent macro usage.
* **Macro removal in `lib/luanetfilter.h`:** Removed definitions of `luanetfilter_setinteger` and `luanetfilter_optinteger`, as their functionality is now handled by `lunatik.h`.
* **Macro replacement in `lib/luaxtable.c`:** Replaced `luanetfilter_setinteger` calls with `lunatik_setinteger` for setting integer …
> move luanetfilter_setinteger/optinteger into lunatik.h

- lunatik.h
This pull request makes a single change to the macro definition in `lunatik.h`, renaming it and simplifying its logic.
* Renamed the macro `lunatik_optinteger` to `luahid_optinteger` and simplified its logic by removing conditional checks for `lua_isnil`. The new implementation directly assigns `opt` if the field is `nil`, reducing redundancy.
> update the optinteger with removed nil version

- config.ld
- lib/luahid.c
This pull request introduces enhancements to the `lib/luahid.c` file, focusing on memory management, Lua table parsing, and improving code clarity. The most significant changes include adding a helper function to parse integer fields from Lua tables, implementing a function to parse `id_table` entries, and updating memory cleanup logic in the `luahid_release` function.
* Added a helper function `get_int_field` to safely retrieve integer fields from Lua tables with a default value fallback.
* Implemented the `luahid_parse_id_table` function to parse the `id_table` field from Lua tables, dynamically allocate memory for HID device IDs, and validate table entries.
* Updated the `luahid_release` function to free the `id_table` field in the HID driver if it is not `NULL`, ensuring proper …
> add dynamic input support for id_table

- lib/luahid.c
This pull request introduces significant enhancements to the `lib/luahid.c` file to improve HID (Human Interface Device) driver functionality. The changes include adding new dependencies, extending the `luahid_t` structure, implementing a `probe` mechanism for device initialization, and modifying the HID driver registration process to support Lua-based device handling.
* **Added new dependencies for Lua and kernel utilities**:
Included `linux/printk.h` and `lua.h` headers to enable logging and Lua integration in the HID driver. 
* **Extended `luahid_t` structure**:
Added a `devtable` member to store device-specific private data, improving the driver's ability to manage multiple devices. 
* **Introduced `luahid_probe` and `luahid_probe_handler`**:
Implemented a `probe` function and its …
> add handler for probe

- lib/luacrypto_comp.c
This pull request updates the `luacrypto_comp.c` file to ensure compatibility with different Linux kernel versions. The changes introduce conditional compilation to handle the deprecation of the `crypto_comp` API in Linux kernel version 6.15 and later.
* Added a version check using `LINUX_VERSION_CODE` to conditionally include the `crypto_comp` module only for kernels below version 6.15. 
* Introduced a preprocessor warning to notify developers that the `crypto_comp` API is removed in Linux kernel versions 6.15 and above.
* Included `<linux/version.h>` to access the `LINUX_VERSION_CODE` macro for kernel version checks.
> Ifdef comp kernelverion

- lib/luadata.c
- lib/luadata.h
- lib/luanetfilter.c
- lib/luanetfilter.h
- lib/luaxdp.c
- lib/luaxtable.c
This pull request refactors the `lunatik_newbuffer` macro to improve reusability and consistency across the codebase. The macro is moved from `lib/luanetfilter.h` to `lunatik.h`, and references to the old `luanetfilter_newbuffer` macro are replaced with the new `lunatik_newbuffer`.
* Removed the `luanetfilter_newbuffer` macro from `lib/luanetfilter.h` and replaced its usage with the `lunatik_newbuffer` macro for consistency. 
* Removed an unused `#include <lunatik.h>` directive from `lib/luadata.h` to streamline the header file.
> moving the newbuffer marco from netfilter to the core

- lib/luahid.c
This pull request introduces enhancements to the HID driver integration in the `lib/luahid.c` file, including the addition of support for report fixups, a new `luadata_t` structure, and improved Lua integration for HID device information. These changes aim to extend the functionality of the driver and improve its interaction with Lua scripts.
* Added the `luahid_report_fixup` function to handle report fixups for HID devices, with support for kernel versions 6.12.0 and above. This function integrates Lua-based processing of HID reports, allowing modifications to the report data.
* Introduced the `luahid_doreport_fixup` helper function to manage the Lua interaction for report fixups, including creating and handling `luadata_t` objects for report data.
* Defined a new `luadata_t` structure …
> add callback for report_descriptor
