luainkernel/lunatik

Kbuild, Makefile, lib/lualinux.c
=> add lib/lualinux

Kbuild, Makefile, bin/lunatik.lua, lib/luadevice.c, lib/lualinux.c, lunatik.h, lunatik_conf.h, lunatik_core.c, lunatik_run.c
* add support for spinlock and GFP_ATOMIC
=> add lunatik_runtime/stop API

README.md, lib/luadevice.c, lib/lualinux.c, lunatik.h, lunatik_core.c, sbin/lunatik
* few adjustments to improve the documentation
* update lua/ submodule
=> add README.md

README.md, examples/shared.lua, lib/luathread.c, lunatik, lunatik.h
* [update README.md](https://github.com/luainkernel/lunatik/commit/4240c3576d5df80d08cd5bf7130a28523c4129d9)
* [run collectgarbage() on lunatik stop <runtime>](https://github.com/luainkernel/lunatik/commit/36522e5df83a8f7dc8b5d9547cdb99848bca2211)
* [use pcall on luathread](https://github.com/luainkernel/lunatik/commit/55e0f395d3fd8603fdb1cd6ed7ccdf5f1aabd21a)
=> add examples/shared

lib/luathread.c, lunatik.h
=> allow threads to finalize themselves

lib/lualinux.c, lib/luathread.c, lunatik_conf.h
* [fix thread termination](https://github.com/luainkernel/lunatik/commit/15deb644dc06b8092de1c0dc1fe16f8174ecc826)
=> add linux.schedule()

Makefile, examples/echod/daemon.lua, examples/echod/worker.lua, lib/lualinux.c, lib/luasocket.c
=> add support for non-block sockets

examples/echod/daemon.lua, lib/luadata.c, lib/luadevice.c, lib/lualinux.c, lib/luanotifier.c, lib/luasocket.c, lib/luathread.c, lunatik_obj.c
* [force methods through monitor](https://github.com/luainkernel/lunatik/commit/1991200df9115845c85f43b4703f8d0d5d51a37a)
* [set TASK_INTERRUPTIBLE as default on linux.schedule()](https://github.com/luainkernel/lunatik/commit/4e3b83b3d8a8c3a0954f66b3b282a6405df5dcfc)
=> fix null-pointer object

lib/luanotifier.c, lib/luarcu.c, lib/luathread.c, lunatik, lunatik.h, lunatik.lua, lunatik_core.c, lunatik_obj.c
* put object in case of error (both on thread and rcu)
* handle runtime termination properly in the driver
* fix synchronization in case of sharing notifier
=> throw error on cloning object if cannot find metatable

Kbuild, Makefile, examples/systrack.lua, lib/luadevice.c, lib/luaprobe.c, lib/luasyscall.c, lib/syscall/table.lua, lunatik, lunatik.h, lunatik_core.c, lunatik_obj.c
* please notice it still might hang during termination because we share mutexes among every CPU
=> fix luaprobe termination and add luasyscall

lunatik
* avoiding writing to an inexistent driver
=> fix lunatik unload

lib/luadata.c, lib/lualinux.c, lib/luanotifier.c, lib/luaprobe.c, lib/luarcu.c, lib/luasyscall.c, lib/luathread.c, lunatik, lunatik.h, lunatik.lua, lunatik_aux.c, lunatik_core.c, lunatik_obj.c
* [allow running non-sleepable rutimes from the command line](https://github.com/luainkernel/lunatik/commit/bd7c9ad0a2d28e92a33d7f10034d5a2dabe5d9cd)
* [avoid requiring lunatik library on non-sleepable runtimes](https://github.com/luainkernel/lunatik/commit/e4e2d1eaddabb72f970408b98396a2dbdcb70437)
* [add support for current and task info on luathread](https://github.com/luainkernel/lunatik/commit/c6c33f069233f9c41668381945d5adf7715a0a5d)
=> allow creating objects that sleep accordingly to runtime sleep property

.gitmodules, Kbuild
* fork klibc on luainkernel
* [disable UBSAN_SANITIZE](https://github.com/luainkernel/lunatik/commit/051071ac7f0cddde490f000c4f805399eaa5585c)
=> fix FPAC exception on arm64's setjmp/longjmp

Makefile, README.md, examples/filter/Makefile, examples/filter/blacklist.lua, examples/filter/https.c, examples/filter/sni.lua, lib/luadata.h, lib/luaxdp.c, lunatik.h, lunatik_obj.c
* add offset parameter on bpf_luaxdp_run
=> add attach/detach APIs to luaxdp

examples/filter/sni.lua, lib/luadata.h, lib/luaxdp.c, lunatik.h
* add LUNATIK_LIB and lunatik_require APIs
=> require luadata on xdp.attach()

Kbuild
* revert `UBSAN_SANITIZE := n`
=> update Lua to v5.4.7 (rc2)

lunatik
=> fix issue #130: write to /dev/lunatik only if it exists

lib/luadata.c, lib/luadata.h, lib/luaxdp.c
This PR allows us to handle const data using luadata.
=> add editable field to luadata

lib/luaxtable.c
Fix a bug that prevented TCP payload to be passed to lua scripts.
=> Fix skb len calculation

lib/luasocket.c
Fix #157 (compilation error with 6.1.80 <= kernel < 6.2).
=> Update kernel version check

README.md
* we are not allowing this anymore because of lunatik_monitor
=> remove <library>.<method>(<object>, ...) calling format from README

examples/echod/daemon.lua, examples/echod/worker.lua, lib/luathread.c
* while here, fixed double thrd:stop() and updated examples/echod
=> drop support to passing args on thread.run()

Makefile, bin/lunatik, driver.lua, lib/luarcu.c, lib/luaxdp.c, lib/lunatik/runner.lua, lunatik.h, lunatik_core.c, lunatik_run.c
* change ENINVAL to ENOEXEC
* replace lunatik.runtimes() with lunatik.runtimes
* require libs automatically on lunatik_pushobject()
=> protect lunatik_runtime() call

tools/Readme.md, tools/debian_kernel_postinst_lunatik.sh
=> Debian: install Lunatik on kernel upgrade

lunatik_core.c
* so we can use lunatik._ENV for softirqs, for instance
=> add lunatik stub lib for non-sleep runtimes

bin/lunatik, lib/lunatik/runner.lua
* e.g., lunatik [run|stop] <script>.lua
=> allow using .lua file extension in the command line

examples/filter/sni.lua
Related to #193 
Could’nt test it, as I don’t have the necessary machines at hand: should be tested before merge.
=> Add netfilter hooks on filter example

Makefile, tools/debian_kernel_postinst_lunatik.sh
- Missed bpftool;
- slight change in Makefile to allow passing target kernel version.
=> Fix Debian kernel upgrade script

Makefile, tools/debian_kernel_postinst_lunatik.sh
I had confused KERNEL_RELEASE and KERNEL_VERSION
=> Fix Debian update script

tools/debian_kernel_postinst_lunatik.sh
Fixes kernel version detection and missing dependencies checks
=> Fixes for Ubuntu

tools/debian_kernel_postinst_lunatik.sh
I had forgotten the `KERNEL_RELEASE` variable for `make install`.
=> Remove old dependency and fix install

.gitignore, Makefile
Makefile action to install / uninstall `ipparse` from Moontastik releases.
=> Ipparse integration

.gitignore, README.md, examples/dnsblock/nf_dnsblock.lua, examples/dnsdoctor/common.lua, examples/dnsdoctor/nf_dnsdoctor.lua, lib/luanetfilter.c, lib/luanetfilter.h, lib/luaxtable.c
- add `dnstest` and `*.so` to the topmost .gitignore
- remove some unused code
- document `xdp.action`
=> a few minor changes

Makefile
fix https://github.com/luainkernel/lunatik/pull/192#issuecomment-2374650775
=> fix bpf and bpf_install Makefile targets

README.md
Tried and tested on fresh Arch linux install, vanilla linux kernel
If there's any more info you would like to know about system please let me know
=> Adding installation instructions for Arch

Makefile, README.md, lib/net.lua, lib/socket/inet.lua
draft: solution for the issue #215
yet to change the docs 
wanted to confirm if this is correct way to implement or is there any other better way
=> adding a net library

lib/luaxdp.c
* bpf_luaxdp_run() could be called before luaxdp_runtimes on luaxdp_attach()
=> fix race condition on luaxdp

Makefile, bin/lunatik
* work around dep order on Ubuntu (duo to ZFS)
=> remove dependency on insmod

Kbuild
* we need klibc includes for building lua source because include/setjmp.h
=> fix cflags

lib/luanetfilter.c, lib/luanetfilter.h
* while here doing a little refactoring
=> add support for setting skb->mark on luanetfilter

examples/dnsdoctor/cleanup.sh
=> fix missing semi-colon in cleanup script
